# GitHub Actions Workflow for Landing Zone Terraform Deployment

name: Foundation Resource Deployment

on:
  workflow_dispatch:
    inputs:
      environment_type:
        description: 'environment Type'
        required: true
        type: choice
        options:
          - dev
          - prod
        default: 'dev'

      subscription_type:
        description: 'Subscription Type'
        required: true
        type: string
        default: ''

      deployment_type:
        description: 'Deployment type( foundation or NSG)'
        required: true
        type: choice
        options:
          - foundation
          - NSG
        default: 'foundation'

      environment:
        description: 'Environment'
        required: true
        type: choice
        options:
          - dev
          - prod
        default: 'dev'

      auto_approve:
        description: 'Auto-approve apply (skip manual approval)'
        required: false
        type: boolean
        default: false